### ISSUE TITLE
Link doesn't pull up a Webpage

### ISSUE THREAD

**Issue by Ricecake-Pony** [learn-co-curriculum/phase-0-html-lists-images-and-links#2]
### Canvas Link

https://learning.flatironschool.com/courses/6022/pages/html-lists-images-and-links?module_item_id=432884#tips

### Concern

The relative link once clicked on navigates to a flatirons.com page to where it states the About html doesn't exist.

**Comment by jlboba** [comment]
Thanks for raising this issue! The lesson in question has been updated in Canvas
for future cohorts.
